---
- name: Install and start Apache (httpd)
  hosts: all
  become: yes

  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present

    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes
